// Condições oficiais do Skyfall RPG (Apêndice A do livro básico), com descrição resumida em texto próprio
export const CONDICOES = [
  { nome: 'Agarrado', descricao: 'Está Contida. Termina se quem agarrou ficar Incapacitado, se sair do alcance do agarramento, ou vencendo um teste de Força contra quem agarra.' },
  { nome: 'Agarrando', descricao: 'Está segurando ativamente outra criatura Agarrada. Move-se com deslocamento reduzido pela metade e precisa manter uma mão ocupada.' },
  { nome: 'Amedrontado', descricao: 'Desvantagem em testes de atributo e ataque. Não consegue se mover por vontade própria em direção à fonte do medo.' },
  { nome: 'Atordoado', descricao: 'Incapacitado, não pode se mover e só consegue balbuciar. Falha automaticamente em testes de Força e Destreza. Fica Desprotegido em todas as proteções.' },
  { nome: 'Caído', descricao: 'Só pode rastejar (a não ser que se levante). Tem desvantagem em ataques. Sofre ataques com vantagem se o atacante estiver bem perto.' },
  { nome: 'Contido', descricao: 'Deslocamento vira 0 e perde bônus de deslocamento. Ataques com desvantagem. Não consegue fazer gestos para conjurar magia. Fica Desprotegido fisicamente.' },
  { nome: 'Desprotegido', descricao: 'Ataques contra a proteção indicada acontecem com vantagem para quem ataca.' },
  { nome: 'Desorientado', descricao: 'Fica Desprotegido. Testes que envolvem os sentidos e ataques realizados são feitos com desvantagem.' },
  { nome: 'Em Chamas', descricao: 'Sofre dano de fogo no início do turno, que aumenta a cada rodada. Precisa gastar uma ação para se apagar.' },
  { nome: 'Encantado', descricao: 'Não consegue atacar quem a encantou. Quem encantou tem vantagem em testes sociais contra ela.' },
  { nome: 'Envenenado', descricao: 'Tem desvantagem em testes.' },
  { nome: 'Incapacitado', descricao: 'Não pode realizar ações nem reações.' },
  { nome: 'Inconsciente', descricao: 'Incapacitada, não se move nem fala, larga o que estiver segurando e fica Caída. Fica Desprotegida; ataques próximos acertam automaticamente e são críticos.' },
  { nome: 'Inspirado', descricao: 'Está sob efeito de uma habilidade de inspiração. Só pode ter um efeito desse tipo por vez.' },
  { nome: 'Invisível', descricao: 'Não pode ser vista sem ajuda mágica ou sentido especial. Ataques contra ela têm desvantagem; os ataques dela têm vantagem.' },
  { nome: 'Marcado', descricao: 'Está sob efeito de uma habilidade ou magia que aplica essa marca, com um contador que aumenta a cada aplicação na cena.' },
  { nome: 'Machucada', descricao: 'Está com pontos de vida iguais ou menores que a metade do total — algumas habilidades reagem a esse estado.' },
  { nome: 'Paralisado', descricao: 'Incapacitada, não se move nem fala. Fica Desprotegida. Ataques bem-sucedidos de perto são automaticamente críticos.' },
  { nome: 'Petrificado', descricao: 'Transformada em pedra: Incapacitada, não percebe o ambiente, tem resistência a todo dano e fica Desprotegida, mas é imune a veneno e doença.' },
  { nome: 'Protegido', descricao: 'Ataques contra a proteção indicada acontecem com desvantagem para quem ataca.' },
  { nome: 'Provocado', descricao: 'Tem desvantagem em ataques contra qualquer criatura que não seja quem a provocou.' },
];
